// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Resolves the connection string regardless of which provider set it.
// Local dev (docker-compose) sets plain DATABASE_URL. Vercel's native
// Postgres integration (Storage tab, Neon-backed) instead auto-injects
// POSTGRES_PRISMA_URL/POSTGRES_URL — this falls back through both naming
// schemes so no manual env var renaming is needed either way.
//
// Note: the installed Prisma version (7.10.0) does not yet support a
// separate `directUrl` in this config file (checked against the actual
// shipped types, not just docs — the field isn't in the Datasource type).
// If `prisma migrate deploy` ever fails against a pooled connection citing
// advisory locks/prepared statements, temporarily point DATABASE_URL at the
// non-pooled connection string for that one deploy, then switch back.
const pooledUrl = process.env.DATABASE_URL || process.env.POSTGRES_PRISMA_URL || process.env.POSTGRES_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: pooledUrl,
  },
});
